services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=supply_chain_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_client_use_datanode_hostname=true
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - "9864:9864"
      - "9866:9866"
      - "9867:9867"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_client_use_datanode_hostname=true
      - HDFS_CONF_dfs_datanode_hostname=datanode
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:9866
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:9864
      - HDFS_CONF_dfs_datanode_ipc_address=0.0.0.0:9867
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
    depends_on:
      - namenode

  postgres:
    image: postgres:16
    container_name: supply_chain_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=supply_chain_db
      - POSTGRES_USER=supply_chain_user
      - POSTGRES_PASSWORD=supply_chain_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  hadoop_namenode:
  hadoop_datanode:
  postgres_data: